/*
  This file is provided under the MIT licence:

  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
# Generated by npins. Do not modify; will be overwritten regularly
let
  # Backwards-compatibly make something that previously didn't take any arguments take some
  # The function must return an attrset, and will unfortunately be eagerly evaluated
  # Same thing, but it catches eval errors on the default argument so that one may still call it with other arguments
  mkFunctor =
    fn:
    let
      e = builtins.tryEval (fn { });
    in
    (if e.success then e.value else { error = fn { }; }) // { __functor = _self: fn; };

  # If the environment variable NPINS_OVERRIDE_${name} is set, then use
  # the path directly as opposed to the fetched source.
  # (Taken from Niv for compatibility)
  mayOverride =
    name: path:
    let
      envVarName = "NPINS_OVERRIDE_${saneName}";
      saneName = builtins.concatStringsSep "_" (
        builtins.concatLists (
          (builtins.filter (x: builtins.isList x && x != [ "" ]) (builtins.split "([a-zA-Z0-9]*)" name))
        )
      );
      ersatz = builtins.getEnv envVarName;
    in
    if ersatz == "" then
      path
    else
      # this turns the string into an actual Nix path (for both absolute and
      # relative paths)
      builtins.trace "Overriding path of \"${name}\" with \"${ersatz}\" due to set \"${envVarName}\"" (
        if builtins.substring 0 1 ersatz == "/" then
          /. + ersatz
        else
          /. + builtins.getEnv "PWD" + "/${ersatz}"
      );

  mkSource =
    name: spec:
    {
      pkgs ? null,
    }:
    assert spec ? type;
    let
      path =
        let
          sharedGitArgs = repo: rec {
            name =
              let
                matched = builtins.match "^.*/([^/]*)(\\.git)?$" url;
                appendShort =
                  if (builtins.match "[a-f0-9]*" spec.revision) != null then
                    "-${builtins.substring 0 7 spec.revision}"
                  else
                    "";
              in
              "${if matched == null then "source" else builtins.head matched}${appendShort}";

            url =
              {
                Git = repo.url;
                GitHub = "https://github.com/${repo.owner}/${repo.repo}.git";
                GitLab = "${repo.server}/${repo.repo_path}.git";
              }
              .${repo.type} or (throw "Unrecognized repository type ${repo.type}");
          };
        in
        (
          if pkgs == null then
            (rec {
              GitRelease = Git;

              Channel = Tarball;

              Git =
                assert spec.repository ? type;
                if spec.url or null != null && !spec.submodules then
                  Tarball
                else
                  (builtins.fetchGit (
                    sharedGitArgs spec.repository
                    // {
                      inherit (spec) submodules;
                      rev = spec.revision;
                      narHash = spec.hash;
                    }
                  )).outPath;

              PyPi = builtins.fetchurl {
                inherit (spec) url;
                sha256 = spec.hash;
              };

              Tarball = builtins.fetchTarball {
                url = spec.locked_url or spec.url;
                sha256 = spec.hash;
              };

              Container = builtins.throw "container sources require passing in a Nixpkgs value: https://github.com/andir/npins/blob/master/README.md#using-the-nixpkgs-fetchers";
            })
          else
            (rec {
              GitRelease = Git;
              Channel = Tarball;

              Git =
                assert spec.repository ? type;
                # At the moment, either it is a plain git repository (which has an url), or it is a GitHub/GitLab repository
                # In the latter case, there we will always be an url to the tarball
                if spec.url != null && !spec.submodules then
                  Tarball
                else
                  pkgs.fetchGit (
                    sharedGitArgs spec.repository
                    // {
                      rev = spec.revision;
                      inherit (spec) hash;
                      fetchSubmodules = spec.submodules;
                    }
                  );

              PyPi = pkgs.fetchurl {
                inherit (spec) url hash;
              };

              Tarball = pkgs.fetchzip {
                inherit (spec) url hash;
                extension = "tar";
              };

              Container = pkgs.dockerTools.pullImage {
                imageName = spec.image_name;
                imageDigest = spec.image_digest;
                finalImageTag = spec.image_tag;
              };
            })
        ).${spec.type} or (builtins.throw "Unknown source type ${spec.type}");
    in
    spec
    // {
      outPath =
        # Run override logic only if impure
        if builtins ? currentSystem then mayOverride name path else path;
    };

in
mkFunctor (
  {
    input ? ./sources.json,
    pkgs ? null,
  }:
  let
    data =
      if builtins.isPath input then
        # while `readFile` will throw an error anyways if the path doesn't exist,
        # we still need to check beforehand because *our* error can be caught but not the one from the builtin
        # *piegames sighs*
        if builtins.pathExists input then
          builtins.fromJSON (builtins.readFile input)
        else
          throw "Input path ${toString input} does not exist"
      else if builtins.isAttrs input then
        input
      else
        throw "Unsupported input type ${builtins.typeOf input}, must be a path or an attrset";
    inherit (data) version;
  in
  if version == 7 then
    builtins.mapAttrs (
      name: spec:
      if pkgs == null then
        #load bearing comment
        mkFunctor (mkSource name spec)
      else
        mkSource name spec { inherit pkgs; }
    ) data.pins
  else
    throw "Unsupported format version ${toString version} in sources.json. Try running `npins upgrade`"
)
